-- =====================================================================
-- Migration 0002 — switch identity provider to libraryyy.com (libraryyy-idp)
-- =====================================================================
-- Voidbunny no longer runs its own Neon Auth instance. libraryyy.com is
-- the IdP. Sign-in flow is a signed-JWT bridge between the two apps.
--
-- Schema changes on `user_profiles`:
--   * `id` was a "logical FK" to neon_auth.user.id. It's now our own UUID,
--     generated by us. We add a DEFAULT gen_random_uuid() so we can do
--     simple INSERTs without supplying an id.
--   * Add `libraryyy_user_id TEXT UNIQUE NOT NULL` — the foreign reference
--     to libraryyy.com's neon_auth.user.id. This is what `sub` in the
--     bridge JWT contains; we upsert profiles by this key.
--
-- The `neon_auth.*` schema in this Neon project is now UNUSED. We don't
-- drop it because Neon manages it. We just ignore it.
--
-- All other tables (subdomains, claim_codes, referrals, audit_log) are
-- unchanged — they still FK to user_profiles.id.
-- =====================================================================

ALTER TABLE user_profiles
  ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE user_profiles
  ADD COLUMN IF NOT EXISTS libraryyy_user_id TEXT;

-- Two-step constraint add: first the unique index (concurrently-safe in
-- the future), then NOT NULL once any seed data is back-filled. The
-- table is empty in main today, so NOT NULL is safe to set immediately.

CREATE UNIQUE INDEX IF NOT EXISTS user_profiles_libraryyy_user_id_idx
  ON user_profiles(libraryyy_user_id);

-- Safety: fail loudly if this migration is replayed against an env that
-- already has rows with NULL libraryyy_user_id. The table is empty on main
-- today, but a future branch or restore could violate that assumption.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM user_profiles WHERE libraryyy_user_id IS NULL) THEN
    RAISE EXCEPTION
      'Cannot apply 0002: % user_profiles rows have NULL libraryyy_user_id — backfill before retrying',
      (SELECT count(*) FROM user_profiles WHERE libraryyy_user_id IS NULL);
  END IF;
END $$;

ALTER TABLE user_profiles
  ALTER COLUMN libraryyy_user_id SET NOT NULL;
