import type { Metadata } from "next";

export const siteConfig = {
  name: "Voidbunny",
  description:
    "Claude Code on your phone, running on a server you own. A self-hosted app for Claude, Codex, and Gemini CLIs — sign in with your subscription, no API keys required.",
  url: "https://voidbunny.xyz",
  // /og-image.png is a 1200x630 capture of the dither-shader hero with the
  // Voidbunny wordmark, optimised to ~11 KB via palette quantisation.
  // Regenerate by temporarily restoring app/og-preview/page.tsx and
  // screenshotting at 1200x630 (see git history for the capture route).
  ogImage: "/og-image.png",
  creator: "@voidbunny",
  authors: [
    {
      name: "Voidbunny",
      url: "https://voidbunny.xyz",
    },
  ],
  keywords: [
    "Claude Code",
    "self-hosted",
    "Codex",
    "Gemini CLI",
    "AI coding agent",
    "mobile dev",
    "Hetzner",
    "open source",
  ],
} as const;

export const baseMetadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.name,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: [...siteConfig.keywords],
  authors: [...siteConfig.authors],
  creator: siteConfig.creator,
  publisher: siteConfig.name,
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    title: siteConfig.name,
    description: siteConfig.description,
    siteName: siteConfig.name,
    images: [
      {
        url: siteConfig.ogImage,
        width: 1200,
        height: 630,
        alt: `${siteConfig.name} — Claude Code, Codex and Gemini on your phone, self-hosted on a server you own.`,
        type: "image/png",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.name,
    description: siteConfig.description,
    creator: siteConfig.creator,
    images: [siteConfig.ogImage],
  },
  // Icons are auto-generated by Next.js from app/favicon.ico, app/icon.png,
  // and app/apple-icon.png. Don't duplicate them here — iOS Safari picks the
  // wrong <link> when two apple-touch-icon tags compete.
  manifest: "/site.webmanifest",
};

/**
 * JSON-LD structured data for the Voidbunny homepage.
 *
 * Bundles Organization, WebSite and SoftwareApplication in one @graph so
 * Google/Bing/DDG can pick up product info and link-search results back to
 * /stats and the GitHub repo. Inlined in app/layout.tsx as a <script type=
 * "application/ld+json"> block.
 */
export const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${siteConfig.url}/#organization`,
      name: siteConfig.name,
      url: siteConfig.url,
      logo: `${siteConfig.url}/logo-512.png`,
      sameAs: [
        "https://github.com/Ingeniiious/voidbunny-app",
      ],
    },
    {
      "@type": "WebSite",
      "@id": `${siteConfig.url}/#website`,
      url: siteConfig.url,
      name: siteConfig.name,
      description: siteConfig.description,
      publisher: { "@id": `${siteConfig.url}/#organization` },
      inLanguage: "en-US",
    },
    {
      "@type": "SoftwareApplication",
      "@id": `${siteConfig.url}/#software`,
      name: siteConfig.name,
      description: siteConfig.description,
      url: siteConfig.url,
      applicationCategory: "DeveloperApplication",
      operatingSystem: "Linux (Ubuntu)",
      // Free MIT-licensed install — model price=0 explicitly so Google
      // doesn't render a fake "$" badge from missing offer data.
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
      },
      license: "https://opensource.org/licenses/MIT",
      author: { "@id": `${siteConfig.url}/#organization` },
      downloadUrl: "https://github.com/Ingeniiious/voidbunny-app",
      softwareRequirements:
        "Ubuntu LTS VPS with systemd; ~2 GB RAM minimum",
    },
  ],
} as const;

export function createMetadata({
  title,
  description,
  path = "/",
  image,
  noIndex = false,
}: {
  title?: string;
  description?: string;
  path?: string;
  image?: string;
  noIndex?: boolean;
}): Metadata {
  const url = `${siteConfig.url}${path}`;
  const ogImage = image ?? siteConfig.ogImage;

  return {
    title,
    description,
    alternates: {
      canonical: path,
    },
    openGraph: {
      title: title ?? siteConfig.name,
      description: description ?? siteConfig.description,
      url,
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: title ?? siteConfig.name,
        },
      ],
    },
    twitter: {
      title: title ?? siteConfig.name,
      description: description ?? siteConfig.description,
      images: [ogImage],
    },
    ...(noIndex && {
      robots: {
        index: false,
        follow: false,
      },
    }),
  };
}
